apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
    kompose.version: 1.37.0 (fb0539e64)
    service: api_panier
    type: api
  labels:
    io.kompose.service: api-panier
  name: api-panier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-panier
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
        kompose.version: 1.37.0 (fb0539e64)
        service: api_panier
        type: api
      labels:
        io.kompose.service: api-panier
    spec:
      containers:
        - image: ghcr.io/uha-sae53/api-panier:latest
          name: api-panier
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
