apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbpanier-persistentvolumeclaim
  labels:
    io.kompose.service: dbpanier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
