apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
    kompose.version: 1.37.0 (fb0539e64)
    logformat: gunicorn
    service: apicatalogue
    type: api
  labels:
    io.kompose.service: apicatalogue
  name: apicatalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apicatalogue
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
        kompose.version: 1.37.0 (fb0539e64)
        logformat: gunicorn
        service: apicatalogue
        type: api
      labels:
        io.kompose.service: apicatalogue
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-for-db
          image: busybox:1.36.1
          imagePullPolicy: Always
          command: ['sh', '-c', 'until nc -z dbcatalogue 3307; do echo waiting for db; sleep 2; done;']
      containers:
        - image: ghcr.io/uha-sae53/api-catalogue:latest
          imagePullPolicy: Always
          name: apicatalogue
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: DB_CATALOGUE_HOST
              value: "dbcatalogue"
            - name: DB_CATALOGUE_PORT
              value: "3307"
            - name: DB_CATALOGUE_NAME
              value: "catalogue"
            - name: DB_CATALOGUE_USER
              value: "root"
            - name: DB_CATALOGUE_PASSWORD
              value: "catalogue"
          volumeMounts:
            - mountPath: /app/projet/media
              name: images-catalogue
      restartPolicy: Always
      volumes:
        - name: images-catalogue
          persistentVolumeClaim:
            claimName: images-catalogue