apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: images-catalogue
  name: images-catalogue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
