apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
    kompose.version: 1.37.0 (fb0539e64)
    service: api_panier
    type: api
  labels:
    io.kompose.service: api-panier
  name: api-panier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-panier
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
        kompose.version: 1.37.0 (fb0539e64)
        service: api_panier
        type: api
      labels:
        io.kompose.service: api-panier
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-for-redis
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z dbpanier 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - image: ghcr.io/uha-sae53/api-panier:latest
          name: api-panier
          ports:
            - containerPort: 8002
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: "dbpanier"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
      restartPolicy: Always