apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  selector:
    matchLabels:
      io.kompose.service: filebeat
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.11.0
          imagePullPolicy: IfNotPresent
          args:
            - filebeat
            - -e
            - -c
            - /usr/share/filebeat/filebeat.yml
            - -strict.perms=false
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: filebeat-cm0
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: true
            - name: varlibdocker
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: filebeat-cm0
          configMap:
            name: filebeat-cm0
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker/containers
            type: DirectoryOrCreate
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
            type: DirectoryOrCreate
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
            type: FileOrCreate
