apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: kibana
  name: kibana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5601
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
            - name: XPACK_SECURITY_ENROLLMENT_ENABLED
              value: "false"
            - name: INTERACTIVESETUP_ENABLED
              value: "false"
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              value: "this_is_a_dummy_key_with_32_chars!"
            - name: SERVER_HOST
              value: "0.0.0.0"
      restartPolicy: Always
