apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./manifests/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  ports:
    - name: "5044"
      port: 5044
      targetPort: 5044
  selector:
    io.kompose.service: filebeat
