# ===== ansible-provisioning/manifests/argocd-apps/frontend-application.yaml =====
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/uha-sae53/frontend/frontend-manager
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.pull-secret: secret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  source:
    path: ansible-provisioning/manifests/frontend
    repoURL: https://github.com/uha-sae53/Vagrant.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---