# Variables globales
[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
k8s_version=1.28
pod_network_cidr=10.244.0.0/16
docker_registry_url=ghcr.io
docker_registry_user=uha-sae53
docker_registry_token=${TOKEN}

# Master node
[master]
vm-master ansible_host=192.168.56.10 hostname=master is_master=true

# Worker nodes
[workers]
vm-slave-1 ansible_host=192.168.56.11 hostname=slave-1 is_master=false
vm-slave-2 ansible_host=192.168.56.12 hostname=slave-2 is_master=false

# Groupe global du cluster
[k8s_cluster:children]
master
workers
