apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-commandes.yml -o ../manifests/
    kompose.version: 1.37.0 (fb0539e64)
    service: api_commandes
    type: api
  labels:
    io.kompose.service: apicommandes
  name: apicommandes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apicommandes
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-commandes.yml -o ../manifests/
        kompose.version: 1.37.0 (fb0539e64)
        service: api_commandes
        type: api
      labels:
        io.kompose.service: apicommandes
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z dbcommandes 3306; do echo waiting for db; sleep 2; done;']
      containers:
        - image: ghcr.io/uha-sae53/api-commandes:latest
          name: apicommandes
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
