[master]
192.168.56.10 ansible_hostname=master

[workers]
192.168.56.11 ansible_hostname=slave-1
192.168.56.12 ansible_hostname=slave-2

[k8s_cluster:children]
master
workers

[k8s_cluster:vars]
ansible_user=vagrant
ansible_become=yes
ansible_python_interpreter=/usr/bin/python3
