Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.ssh.insert_key = true
  
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus = 4
    libvirt.cpu_mode = "host-passthrough"
    libvirt.management_network_name = "vagrant-libvirt"
    libvirt.management_network_address = "192.168.56.0/24"
  end
  
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false
  
  config.vm.define "vm-master", primary: true do |vm|
    vm.vm.network "private_network", 
      ip: "192.168.56.10",
      libvirt__network_name: "vagrant-libvirt"
    vm.vm.hostname = "master"
  end
  
  (1..2).each do |i|
    config.vm.define "vm-slave-#{i}" do |vm|
      vm.vm.network "private_network", 
        ip: "192.168.56.1#{i}",
        libvirt__network_name: "vagrant-libvirt"
      vm.vm.hostname = "slave-#{i}"
      vm.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y qemu-guest-agent
        systemctl enable qemu-guest-agent
        systemctl start qemu-guest-agent
      SHELL
    end
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "playbook.yml"
    ansible.groups = {
      "master" => ["vm-master"],
      "workers" => ["vm-slave-1", "vm-slave-2"],
      "k8s_cluster:children" => ["master", "workers"]
    }
  end
end