name: K8S YAML Manifest Lint
on:
    push:
        branches:
            - main
            - 'release/*'
    pull_request:
        branches:
            - main

jobs:
  yamllint:
    name: Lint Kubernetes YAML Manifests
    runs-on: ubuntu-latest

    steps:
      - name: Verification du code
        uses: actions/checkout@v3

      - name: Installation de KubeLinter
        run: |
          curl -sSL https://raw.githubusercontent.com/upciti/wakemeops/main/assets/install_repository | sudo bash
          sudo apt install kubelinter

      - name: Lancer KubeLinter
        run: kubelinter lint Vagrant/ansible-provisioning/manifests/ Vagrant/shell-provisioning/manifests/ | tee kube-linter-report.txt

      - name: Afficher les resultats
        run: cat kube-linter-report.txt