name: K8S YAML Manifest Lint

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  yamllint:
    name: Lint Kubernetes YAML Manifests
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du code
        uses: actions/checkout@v3

      - name: Installer KubeLinter via Go
        run: |
          sudo apt-get update
          sudo apt-get install -y golang
          go install golang.stackrox.io/kube-linter/cmd/kube-linter@latest
          export PATH=$PATH:$HOME/go/bin
          kube-linter version

      - name: Lancer KubeLinter
        run: |
          kubelinter lint Vagrant/ansible-provisioning/manifests/ Vagrant/shell-provisioning/manifests/ | tee kube-linter-report.txt

      - name: Afficher les résultats
        run: cat kube-linter-report.txt
